use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Check for banned macros in src/ and tests/
    let src_dir = Path::new("src");
    let tests_dir = Path::new("tests");

    let mut violations = Vec::new();

    if src_dir.exists() {
        check_directory(&src_dir, &mut violations);
    }

    if tests_dir.exists() {
        check_directory(&tests_dir, &mut violations);
    }

    if !violations.is_empty() {
        println!("cargo:warning=❌ Found banned macro usage (use tracing macros instead):");
        for (file, line_num, line) in &violations {
            println!(
                "cargo:warning=  {}:{} - {}",
                file.display(),
                line_num,
                line.trim()
            );
        }
        panic!("Found {} banned macro violations", violations.len());
    }

    // Generate CLI commands list for tests
    generate_cli_commands_list();
}

fn generate_cli_commands_list() {
    // Parse the cli_commands! macro invocation in src/cli.rs to extract all command names.
    // This generates a constant that integration tests use to verify 100% test coverage.
    // If a developer adds a command to the macro but forgets to test it, the build fails.
    let cli_rs_content = fs::read_to_string("src/cli.rs").expect("Failed to read src/cli.rs");

    // Find the cli_commands! invocation and extract command names
    let commands = extract_command_names(&cli_rs_content);

    // Generate the shared file
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("cli_commands.rs");

    let content = format!(
        "// Generated by build.rs - DO NOT EDIT\n\
         // All CLI commands from macro definition\n\
         pub const ALL_CLI_COMMANDS: &[&str] = &{:?};\n",
        commands
    );

    fs::write(&dest_path, content).expect("Failed to write cli_commands.rs");

    println!("cargo:rerun-if-changed=src/cli.rs");
}

fn extract_command_names(content: &str) -> Vec<String> {
    let mut commands = Vec::new();
    let mut in_macro = false;
    let mut in_string_commands = false;
    let mut in_flag_commands = false;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("cli_commands!") {
            in_macro = true;
            continue;
        }

        if in_macro {
            if trimmed.starts_with("string_commands:") {
                in_string_commands = true;
                in_flag_commands = false;
                continue;
            } else if trimmed.starts_with("flag_commands:") {
                in_string_commands = false;
                in_flag_commands = true;
                continue;
            } else if trimmed.starts_with("supporting_fields:") {
                in_string_commands = false;
                in_flag_commands = false;
                continue;
            } else if trimmed == "}" {
                break;
            }

            if (in_string_commands || in_flag_commands) && trimmed.starts_with("(") {
                // Extract snake_case name from tuple - it's the last quoted string
                if let Some(snake_name) = extract_snake_case_name(trimmed) {
                    commands.push(snake_name);
                }
            }
        }
    }

    commands
}

fn extract_snake_case_name(line: &str) -> Option<String> {
    // Find all quoted strings in the line
    let mut quotes = Vec::new();
    let mut in_quote = false;
    let mut start = 0;

    for (i, ch) in line.char_indices() {
        if ch == '"' {
            if in_quote {
                quotes.push(&line[start + 1..i]);
                in_quote = false;
            } else {
                start = i;
                in_quote = true;
            }
        }
    }

    // The snake_case name is the last quoted string before the closing parenthesis
    quotes.last().map(|s| s.to_string())
}

fn check_directory(dir: &Path, violations: &mut Vec<(std::path::PathBuf, usize, String)>) {
    for entry in fs::read_dir(dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();

        if path.is_dir() {
            check_directory(&path, violations);
        } else if path.extension().and_then(|s| s.to_str()) == Some("rs") {
            let content = fs::read_to_string(&path).unwrap();

            for (line_num, line) in content.lines().enumerate() {
                let trimmed = line.trim();

                // Skip comments
                if trimmed.starts_with("//") || trimmed.starts_with("/*") {
                    continue;
                }

                // Check for banned macros (using concat to avoid self-detection)
                // We check for the macro name followed by ! and then either space or paren
                let banned_prefixes = [
                    concat!("print", "ln", "!"),
                    concat!("eprint", "ln", "!"),
                    concat!("print", "!"),
                    concat!("eprint", "!"),
                    concat!("dbg", "!"),
                ];

                for prefix in &banned_prefixes {
                    // Check if line contains the macro (must be followed by paren or space)
                    if let Some(pos) = line.find(prefix) {
                        // Get the character after the macro name
                        let after_macro = line.chars().nth(pos + prefix.len());
                        // It's a macro call if followed by '(' or whitespace
                        if matches!(after_macro, Some('(') | Some(' ') | Some('\t') | None) {
                            violations.push((path.clone(), line_num + 1, line.to_string()));
                            break;
                        }
                    }
                }
            }
        }
    }
}
