[app]
benchmark = true  # show performance metrics
debug = true  # show debug logs
prompt = false  # show prompts
response = false  # show responses
delete_logs = false  # delete logs on shutdown
file_reset = true  # move processed documents back to input_documents on startup

[environment]
manage_venv = true  # let Cymbiont manage the Python environment
