[models]
# Anthropic models: claude-3-5-sonnet-latest, claude-3-5-haiku-latest
# OpenAI models: gpt-4o, gpt-4o-mini, o1-preview
CHAT_AGENT_MODEL = "claude-3-5-sonnet-latest"  # main chat and tool-calling agent
TAG_EXTRACTION_MODEL = "claude-3-5-haiku-latest"  # bulk document processing for knowledge graph pipeline
PROGRESSIVE_SUMMARY_MODEL = "claude-3-5-haiku-latest"  # summarizes chat history for the chat agent
REVISION_MODEL = "claude-3-5-sonnet-latest"  # used for revise_document tool

[app]
token_logging = false  # show token usage
benchmark = false  # show performance metrics
debug = false  # show debug logs
prompt = false  # show prompts
response = false  # show responses
tool = false  # show tool calls
delete_logs = false  # delete logs on shutdown
file_reset = false  # move processed documents back to input_documents on startup

[shell]
user_name = "user" 
agent_name = "chat_agent" 
agent_activation_mode = "as_needed" # Options: "continuous" or "as_needed"

[environment]
manage_venv = true  # let Cymbiont manage the Python environment
