[app]
token_logging = false  # show token usage
benchmark = false  # show performance metrics
debug = false  # show debug logs
prompt = false  # show prompts
response = false  # show responses
delete_logs = false  # delete logs on shutdown
file_reset = false  # move processed documents back to input_documents on startup

[shell]
user_name = "user"  # name shown in shell prompt
agent_name = "chat_agent"  # name shown for AI responses

[environment]
manage_venv = true  # let Cymbiont manage the Python environment