//! CLI Command Handling Module
//!
//! This module contains all CLI argument parsing and command execution logic
//! for Cymbiont. It handles agent management, graph operations, and various
//! administrative commands through a clean command-line interface.
//!
//! ## Architecture
//!
//! The CLI module is responsible for:
//! - Parsing command-line arguments using clap
//! - Executing one-off commands (agent/graph management)
//! - Displaying system status when no commands are provided
//! - Determining whether to exit after command completion
//!
//! ## Concurrency Considerations
//!
//! Authorization operations that modify both agent and graph registries use
//! `lock_registries_for_write()` to acquire locks in the canonical
//! order (graph_registry → agent_registry) preventing potential deadlocks
//!
//! ## Single Source of Truth: The `cli_commands!` Macro
//!
//! All CLI commands are defined exhaustively in a single macro invocation that
//! generates the Args struct, JSON parsing, and contract enforcement. This ensures
//! compile-time verification that all commands are properly implemented and tested.
//!
//! ### Adding a New CLI Command
//!
//! When adding a new command, follow these steps:
//!
//! 1. **Add to the macro** in this file:
//!    ```rust
//!    cli_commands! {
//!        string_commands: [
//!            // Add your command here if it takes a string argument
//!            (ExportGraph, path, export_graph, "PATH", "export_graph"),
//!        ],
//!        flag_commands: [
//!            // Or here if it's a boolean flag
//!            (ShowVersion, show_version, "", "show_version"),
//!        ],
//!    }
//!    ```
//!
//! 2. **Implement the handler** in `handle_cli_commands()`:
//!    ```rust
//!    if let Some(export_path) = &args.export_graph {
//!        // Your implementation here
//!        return Ok(true);  // Exit after, or Ok(false) to continue
//!    }
//!    ```
//!
//! 3. **Write integration test** in `tests/integration/cli_commands.rs`:
//!    - Add test case for the command
//!    - Add command name to `TESTED_COMMANDS` array
//!
//! 4. **Build fails if you forget tests!** The build script extracts all commands
//!    from the macro and integration tests verify 100% coverage. Missing tests
//!    will cause a compile-time failure with a clear message.
//!
//! ### Macro Structure
//!
//! The macro takes three categories of definitions:
//! - `string_commands`: Commands that accept a string value (paths, names, IDs)
//! - `flag_commands`: Boolean flags that don't take arguments  
//! - `supporting_fields`: Helper fields for complex commands (e.g., --for-graph)
//!
//! Each command tuple contains:
//! - Variant name for internal use
//! - Field name in JSON (for WebSocket bridge)
//! - Args struct field name
//! - Clap value name for help text
//! - Snake_case command name string
//!
//! ## Command Categories
//!
//! ### Graph Operations
//! - Import Logseq graphs from directories
//! - Delete graphs by name or ID
//! - List all graphs with metadata
//!
//! ### Agent Management
//! - Create/delete agents
//! - Activate/deactivate agents (memory management)
//! - Display agent information
//!
//! ### Agent Authorization
//! - Authorize agents for specific graphs
//! - Deauthorize agents from graphs
//! - Manage multi-agent access control
//!
//! ## Execution Model
//!
//! Commands that modify state (create/delete/authorize) typically cause the
//! program to exit after completion. Import and status commands allow the
//! program to continue running, supporting the persistent daemon model.
//!
//! ## WebSocket Bridge
//!
//! The macro generates `from_json_with_args()` which enables WebSocket clients
//! to execute CLI commands via JSON messages. This provides a unified interface
//! for both command-line and programmatic access.

use std::sync::Arc;
use clap::Parser;
use tracing::{info, error};
use uuid::Uuid;
use crate::error::*;
use crate::lock::{RwLockExt, AsyncRwLockExt, lock_registries_for_write};
use crate::app_state::AppState;
use crate::graph_operations::GraphOps;
use crate::import;

/// CLI Commands Contract Enforcement Macro
/// Developer must specify ALL CLI commands exhaustively
/// This ensures single source of truth and compile-time contract checking
macro_rules! cli_commands {
    (
        string_commands: [
            $(($str_variant:ident, $str_field:ident, $str_args_field:ident, $str_clap:literal, $str_snake:literal)),* $(,)?
        ],
        flag_commands: [
            $(($flag_variant:ident, $flag_args_field:ident, $flag_clap:literal, $flag_snake:literal)),* $(,)?
        ],
        supporting_fields: [
            $(($sup_field:ident, $sup_clap:literal, $sup_requires:literal)),* $(,)?
        ],
    ) => {
        /// CLI arguments - GENERATED BY MACRO from exhaustive command definitions
        #[derive(Parser, Debug)]
        #[command(author, version, about, long_about = None)]
        pub struct Args {
            /// Run as HTTP/WebSocket server
            #[arg(long)]
            pub server: bool,
            
            /// Override data directory path (defaults to config value)
            #[arg(long)]
            pub data_dir: Option<String>,
            
            /// Path to configuration file
            #[arg(long)]
            pub config: Option<String>,
            
            /// Run server for a specific duration in seconds (for testing)
            #[arg(long)]
            pub duration: Option<u64>,
            
            // Generated string command fields
            $(
                #[arg(long, value_name = $str_clap)]
                pub $str_args_field: Option<String>,
            )*
            
            // Generated flag command fields
            $(
                #[arg(long)]
                pub $flag_args_field: bool,
            )*
            
            // Supporting fields for complex commands
            $(
                #[arg(long, value_name = $sup_clap, requires = $sup_requires)]
                pub $sup_field: Option<String>,
            )*
        }
        
        impl Default for Args {
            fn default() -> Self {
                Self {
                    server: false,
                    data_dir: None,
                    config: None,
                    duration: None,
                    $(
                        $str_args_field: None,
                    )*
                    $(
                        $flag_args_field: false,
                    )*
                    $(
                        $sup_field: None,
                    )*
                }
            }
        }
        
        /// Convert CLI command from JSON with supporting fields - GENERATED BY MACRO
        pub fn from_json_with_args(command_name: &str, params: &serde_json::Value) -> std::result::Result<Args, String> {
            let mut args = Args::default();
            
            // Parse the main command
            match command_name {
                $(
                    $str_snake => {
                        let field_val = params[stringify!($str_field)].as_str()
                            .ok_or(concat!("Missing ", stringify!($str_field)))?.to_string();
                        args.$str_args_field = Some(field_val);
                    }
                )*
                $(
                    $flag_snake => {
                        args.$flag_args_field = true;
                    }
                )*
                _ => return Err(format!("Unknown command: {}", command_name)),
            }
            
            // Parse supporting fields from JSON if present
            $(
                if let Some(val) = params[stringify!($sup_field)].as_str() {
                    args.$sup_field = Some(val.to_string());
                }
            )*
            
            Ok(args)
        }
        
    };
}


// SINGLE SOURCE OF TRUTH: All CLI commands defined exhaustively
cli_commands! {
    string_commands: [
        (ImportLogseq, path, import_logseq, "PATH", "import_logseq"),
        (DeleteGraph, identifier, delete_graph, "NAME_OR_ID", "delete_graph"),
        (CreateAgent, name, create_agent, "NAME", "create_agent"),
        (DeleteAgent, identifier, delete_agent, "NAME_OR_ID", "delete_agent"),
        (ActivateAgent, identifier, activate_agent, "NAME_OR_ID", "activate_agent"),
        (DeactivateAgent, identifier, deactivate_agent, "NAME_OR_ID", "deactivate_agent"),
        (AgentInfo, identifier, agent_info, "NAME_OR_ID", "agent_info"),
        (AuthorizeAgent, agent, authorize_agent, "AGENT_NAME_OR_ID", "authorize_agent"),
        (DeauthorizeAgent, agent, deauthorize_agent, "AGENT_NAME_OR_ID", "deauthorize_agent"),
    ],
    flag_commands: [
        (ListGraphs, list_graphs, "", "list_graphs"),
    ],
    supporting_fields: [
        (agent_description, "DESCRIPTION", "create_agent"),
        (for_graph, "GRAPH_NAME_OR_ID", "authorize_agent"),
        (from_graph, "GRAPH_NAME_OR_ID", "deauthorize_agent"),
    ],
}




// Dispatcher for WebSocket bridge (only in debug builds for testing)
#[cfg(debug_assertions)]
pub async fn dispatch_cli_command(
    app_state: &std::sync::Arc<AppState>,
    command_name: &str,
    params: &serde_json::Value,
) -> Result<bool> {
    let args = match from_json_with_args(command_name, params) {
        Ok(args) => args,
        Err(e) => {
            tracing::error!("Failed to parse CLI command: {}", e);
            return Err(CymbiontError::Other(e));
        }
    };
    
    let result = handle_cli_commands(app_state, &args).await;
    result
}


/// Handle all CLI-specific commands
/// Returns true if should exit after command completion
pub async fn handle_cli_commands(app_state: &Arc<AppState>, args: &Args) -> Result<bool> {
    // Handle Logseq import if requested (continues running after)
    if let Some(logseq_path) = &args.import_logseq {
        let import_start = std::time::Instant::now();
        let path = std::path::Path::new(&logseq_path);
        let result = import::import_logseq_graph(&app_state, path, None).await?;
        
        // Report any errors that occurred during import
        if !result.errors.is_empty() {
            error!("Import completed with {} errors:", result.errors.len());
            for err in &result.errors {
                error!("  - {}", err);
            }
        }
        
        info!("✅ Import complete in {:.3}s", import_start.elapsed().as_secs_f64());
        // Don't return true - continue running
    }
    
    // Handle graph deletion if requested (continues running after)
    if let Some(graph_identifier) = &args.delete_graph {
        // Resolve the graph using centralized logic
        let graph_uuid = {
            let registry = app_state.graph_registry.read_or_panic("delete graph - read registry");
            
            // Try to parse as UUID first
            let uuid_opt = Uuid::parse_str(&graph_identifier).ok();
            
            // Use resolve_graph_target to handle both UUID and name
            registry.resolve_graph_target(
                uuid_opt.as_ref(),
                if uuid_opt.is_none() { Some(&graph_identifier) } else { None },
                false  // No smart default for delete
            )?
        };
        
        info!("🗑️  Deleting graph: {}", graph_identifier);
        
        // Delete the graph using GraphOperations extension
        app_state.delete_graph(&graph_uuid).await?;
        
        info!("✅ Graph deleted successfully");
        // Don't return true - continue running
    }
    
    // Handle agent admin commands (these exit after completion)
    
    // Create agent
    if let Some(agent_name) = &args.create_agent {
        let agent_info = {
            let mut registry = app_state.agent_registry.write_or_panic("create agent - write registry");
            
            registry.register_agent(
                None,  // Let it generate a new UUID
                Some(agent_name.clone()),
                args.agent_description.clone(),
            )?
        };
        
        // Create the actual Agent instance
        {
            use crate::agent::{agent::Agent, llm::LLMConfig};
            
            // Ensure agent directory exists
            std::fs::create_dir_all(&agent_info.data_path)?;
            
            // Create agent with default MockLLM config
            let mut agent = Agent::new(
                agent_info.id,
                agent_name.clone(),
                LLMConfig::default(),  // MockLLM by default
                agent_info.data_path.clone(),
                args.agent_description.clone().or(Some("An intelligent assistant".to_string())),
            );
            
            // Save the agent to disk
            agent.save()?;
        }
        
        // Save the registry after creating agent
        {
            let registry = app_state.agent_registry.read_or_panic("create agent - read registry for save");
            registry.save()?;
        }
        
        info!("✅ Created agent '{}' with ID: {}", agent_info.name, agent_info.id);
    }
    
    // Delete agent
    if let Some(agent_identifier) = &args.delete_agent {
        let resolved_id = {
            let registry = app_state.agent_registry.read_or_panic("delete agent - read registry");
            
            // Try to parse as UUID first
            let uuid_opt = Uuid::parse_str(&agent_identifier).ok();
            
            registry.resolve_agent_target(
                uuid_opt.as_ref(),
                if uuid_opt.is_none() { Some(&agent_identifier) } else { None },
                false  // No smart default for delete
            )?
        };
        
        // Don't allow deleting the prime agent
        {
            let registry = app_state.agent_registry.read_or_panic("delete agent - check prime");
            if Some(resolved_id) == registry.get_prime_agent_id() {
                return Err("Cannot delete the prime agent".into());
            }
        }
        
        // Remove agent from memory if loaded
        app_state.deactivate_agent(&resolved_id).await?;
        
        // Remove from registry and archive data
        {
            let mut registry = app_state.agent_registry.write_or_panic("delete agent - write registry");
            registry.remove_agent(&resolved_id)?;
        }
        
        // Save registry after deletion
        {
            let registry = app_state.agent_registry.read_or_panic("delete agent - save registry");
            registry.save()?;
        }
        
        info!("✅ Deleted agent: {}", resolved_id);
    }
    
    // Activate agent
    if let Some(agent_identifier) = &args.activate_agent {
        let resolved_id = {
            let registry = app_state.agent_registry.read_or_panic("read agent registry");
            
            // Try to parse as UUID first
            let uuid_opt = Uuid::parse_str(&agent_identifier).ok();
            
            registry.resolve_agent_target(
                uuid_opt.as_ref(),
                if uuid_opt.is_none() { Some(&agent_identifier) } else { None },
                false  // No smart default for activate
            )?
        };
        
        app_state.activate_agent(&resolved_id).await
            ?;
        
        info!("✅ Activated agent: {}", resolved_id);
    }
    
    // Deactivate agent
    if let Some(agent_identifier) = &args.deactivate_agent {
        let resolved_id = {
            let registry = app_state.agent_registry.read_or_panic("read agent registry");
            
            // Try to parse as UUID first
            let uuid_opt = Uuid::parse_str(&agent_identifier).ok();
            
            registry.resolve_agent_target(
                uuid_opt.as_ref(),
                if uuid_opt.is_none() { Some(&agent_identifier) } else { None },
                false  // No smart default for deactivate
            )?
        };
        
        // Don't allow deactivating the prime agent if it's the only active agent
        {
            let registry = app_state.agent_registry.read_or_panic("read agent registry");
            if Some(resolved_id) == registry.get_prime_agent_id() {
                let active_agents = registry.get_active_agents();
                if active_agents.len() == 1 {
                    return Err("Cannot deactivate the prime agent when it's the only active agent".into());
                }
            }
        }
        
        app_state.deactivate_agent(&resolved_id).await
            ?;
        
        info!("✅ Deactivated agent: {}", resolved_id);
    }
    
    // Authorize agent for graph
    if let Some(agent_identifier) = &args.authorize_agent {
        // Resolve agent (no smart default for authorize)
        let resolved_agent_id = {
            let registry = app_state.agent_registry.read_or_panic("read agent registry");
            
            // Try to parse as UUID first
            let uuid_opt = Uuid::parse_str(&agent_identifier).ok();
            
            registry.resolve_agent_target(
                uuid_opt.as_ref(),
                if uuid_opt.is_none() { Some(&agent_identifier) } else { None },
                false  // No smart default for authorize
            )?
        };
        
        // Resolve graph (requires --for-graph)
        let graph_identifier = args.for_graph.as_deref()
            .ok_or_else(|| "Must specify --for-graph with --authorize-agent")?;
        
        let resolved_graph_id = {
            let registry = app_state.graph_registry.read_or_panic("read graph registry");
            
            // Try to parse as UUID first
            let uuid_opt = Uuid::parse_str(&graph_identifier).ok();
            
            registry.resolve_graph_target(
                uuid_opt.as_ref(),
                if uuid_opt.is_none() { Some(&graph_identifier) } else { None },
                false  // No smart default for graph
            )?
        };
        
        // Authorize agent for graph
        {
            let (mut graph_registry, mut agent_registry) = lock_registries_for_write(
                &app_state.graph_registry,
                &app_state.agent_registry
            )
                ?;
            
            agent_registry.authorize_agent_for_graph(
                &resolved_agent_id,
                &resolved_graph_id,
                &mut graph_registry,
            )?;
        }
        
        // Save both registries
        {
            let registry = app_state.agent_registry.read_or_panic("read agent registry");
            registry.save()
                ?;
        }
        {
            let registry = app_state.graph_registry.read_or_panic("read graph registry");
            registry.save()
                ?;
        }
        
        info!("✅ Authorized agent {} for graph {}", resolved_agent_id, resolved_graph_id);
    }
    
    // Deauthorize agent from graph
    if let Some(agent_identifier) = &args.deauthorize_agent {
        // Resolve agent (no smart default for deauthorize)
        let resolved_agent_id = {
            let registry = app_state.agent_registry.read_or_panic("read agent registry");
            
            // Try to parse as UUID first
            let uuid_opt = Uuid::parse_str(&agent_identifier).ok();
            
            registry.resolve_agent_target(
                uuid_opt.as_ref(),
                if uuid_opt.is_none() { Some(&agent_identifier) } else { None },
                false  // No smart default for deauthorize
            )?
        };
        
        // Resolve graph (requires --from-graph)
        let graph_identifier = args.from_graph.as_deref()
            .ok_or_else(|| "Must specify --from-graph with --deauthorize-agent")?;
        
        let resolved_graph_id = {
            let registry = app_state.graph_registry.read_or_panic("read graph registry");
            
            // Try to parse as UUID first
            let uuid_opt = Uuid::parse_str(&graph_identifier).ok();
            
            registry.resolve_graph_target(
                uuid_opt.as_ref(),
                if uuid_opt.is_none() { Some(&graph_identifier) } else { None },
                false  // No smart default for graph
            )?
        };
        
        // Deauthorize agent from graph
        {
            let (mut graph_registry, mut agent_registry) = lock_registries_for_write(
                &app_state.graph_registry,
                &app_state.agent_registry
            )
                ?;
            
            agent_registry.deauthorize_agent_from_graph(
                &resolved_agent_id,
                &resolved_graph_id,
                &mut graph_registry,
            )?;
        }
        
        // Save both registries
        {
            let registry = app_state.agent_registry.read_or_panic("read agent registry");
            registry.save()
                ?;
        }
        {
            let registry = app_state.graph_registry.read_or_panic("read graph registry");
            registry.save()
                ?;
        }
        
        info!("✅ Deauthorized agent {} from graph {}", resolved_agent_id, resolved_graph_id);
    }
    
    // Show agent info
    if let Some(agent_identifier) = &args.agent_info {
        // Resolve agent (allows smart default to prime if not specified)
        let resolved_id = {
            let registry = app_state.agent_registry.read_or_panic("read agent registry");
            
            // Try to parse as UUID first
            let uuid_opt = Uuid::parse_str(&agent_identifier).ok();
            
            registry.resolve_agent_target(
                uuid_opt.as_ref(),
                if uuid_opt.is_none() { Some(&agent_identifier) } else { None },
                true  // Allow smart default (prime agent) for info command
            )?
        };
        
        // Get agent info from registry
        let (agent_info, is_active) = {
            let registry = app_state.agent_registry.read_or_panic("read agent registry");
            
            let info = registry.get_agent(&resolved_id)
                .ok_or_else(|| format!("Agent {} not found", resolved_id))?
                .clone();
            let active = registry.is_agent_active(&resolved_id);
            (info, active)
        };
        
        // Display agent information
        info!("🤖 Agent Information");
        info!("  ID: {}", agent_info.id);
        info!("  Name: {}", agent_info.name);
        if let Some(desc) = &agent_info.description {
            info!("  Description: {}", desc);
        }
        info!("  Is Prime: {}", agent_info.is_prime);
        info!("  Is Active: {}", is_active);
        info!("  Created: {}", agent_info.created);
        info!("  Last Active: {}", agent_info.last_active);
        
        // Show authorized graphs
        if !agent_info.authorized_graphs.is_empty() {
            info!("  Authorized Graphs:");
            let graph_registry = app_state.graph_registry.read_or_panic("read graph registry");
            
            for graph_id in &agent_info.authorized_graphs {
                if let Some(graph) = graph_registry.get_graph(graph_id) {
                    info!("    - {} ({})", graph.name, graph_id);
                } else {
                    info!("    - {} (not found)", graph_id);
                }
            }
        } else {
            info!("  Authorized Graphs: None");
        }
        
        // Show conversation stats if agent is loaded
        if is_active {
            let agents = app_state.agents.read_or_panic("show agent status - read agents").await;
            if let Some(agent) = agents.get(&resolved_id) {
                info!("  Conversation Messages: {}", agent.conversation_history.len());
            }
        }
        
    }
    
    // List graphs
    if args.list_graphs {
        let graphs = app_state.list_graphs().await
            ?;
        
        if graphs.is_empty() {
            info!("📊 No graphs found");
        } else {
            info!("📊 Found {} graph(s):", graphs.len());
            for graph in &graphs {
                info!("  ID: {}", graph["id"]);
                info!("  Name: {}", graph["name"]);
                if let Some(desc) = graph["description"].as_str() {
                    info!("  Description: {}", desc);
                }
                info!("  Created: {}", graph["created"]);
                info!("  Last Accessed: {}", graph["last_accessed"]);
                info!("");
            }
        }
    }
    
    // If no commands, show status
    show_cli_status(app_state).await?;
    
    Ok(false)
}

/// Show CLI status information
pub async fn show_cli_status(app_state: &Arc<AppState>) -> Result<()> {
    let graphs = {
        let registry_guard = app_state.graph_registry.read_or_panic("show cli status - graph registry");
        registry_guard.get_all_graphs()
    };
    
    if graphs.is_empty() {
        info!("📊 No graphs found");
    } else {
        info!("📊 Found {} registered graph(s)", graphs.len());
    }
    
    // Get open graphs
    let open_graphs = app_state.list_open_graphs().await
        ?;
    
    if !open_graphs.is_empty() {
        {
            let registry_guard = app_state.graph_registry.read_or_panic("show cli status - graph registry");
            info!("📂 {} open graph(s):", open_graphs.len());
            for graph_id in &open_graphs {
                if let Some(graph_info) = registry_guard.get_graph(graph_id) {
                    info!("  - {} ({})", graph_info.name, graph_info.id);
                }
            }
        } // registry_guard drops here
    } else {
        info!("📂 No open graphs");
    }
    
    Ok(())
}

